image: golang:1.16

variables:
  DOCKER_IMAGE: registry.gitlab.com/htdvisser/ssh-gateway
  GOPROXY: https://proxy.golang.org
  GO111MODULLE: 'on'

stages:
- test
- build
- release

test:
  stage: test
  script:
  - go test -cover -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go fmt ./...

build:
  stage: build
  artifacts:
    paths:
    - dist
  script:
  - if [[ ! -d dist ]]; then mkdir dist; fi
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build
  - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 make build
  - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 make build

docker:
  stage: release
  image: docker:git
  services:
  - docker:dind
  before_script:
  - export DOCKER_BRANCH=$(echo $CI_COMMIT_REF_NAME | sed 's:/:-:g')
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t $DOCKER_IMAGE:$DOCKER_BRANCH .
  - docker push $DOCKER_IMAGE:$DOCKER_BRANCH
